export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE'
export const SET_CURRENT_THEME = 'SET_CURRENT_THEME'
export const SET_USER_INFO = "SET_USER_INFO"
export const SET_MEDIA_ID = "SET_MEDIA_ID"
export const SET_DEVICE_ID = "SET_DEVICE_ID"
export const SET_USER_NAME = "SET_USER_NAME"
export const SET_PASSWORD = "SET_PASSWORD"
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER"
export const SET_NATIONAL_ID_FRONT = "SET_NATIONAL_ID_FRONT"
export const SET_NATIONAL_ID_BACK = "SET_NATIONAL_ID_BACK"
export const SET_SELFIE = "SET_SELFIE"
export const SET_NATIONAL_ID_DATA = "SET_NATIONAL_ID_DATA"
export const SET_RESGISTRATION_ACCESS_TOKEN = "SET_RESGISTRATION_ACCESS_TOKEN"
export const SET_RESGISTRATION_FULL_NAME = "SET_RESGISTRATION_FULL_NAME"
export const SET_PROFILE_PHOTO = "SET_PROFILE_PHOTO"
export const SET_CARD_DETAILS = "SET_CARD_DETAILS"
export const RESET_REGISTRATION_DATA = "RESET_REGISTRATION_DATA"
export const SET_CONFIGURATIONS = "SET_CONFIGURATIONS"
export const SET_VERIFICATION_FLOW_ACCESS_TOKEN = "SET_VERIFICATION_FLOW_ACCESS_TOKEN"
export const RESET_VERIFICATION_FLOW_ACCESS_TOKEN = "RESET_VERIFICATION_FLOW_ACCESS_TOKEN"






